#ifndef CONFIG_H
#define CONFIG_H

#include "config_sign_classification.h"
#include "config_lane_detection.h"

#define IMG_MAX_SIZE 384

// #define DISABLE_LANE_DETECTOR
#define DISABLE_GPS_READER

#define SMARTCAM_DEBUG

// Show lane debug images
// #define DEBUG_LANE_DETECTOR_SHOW_LINES
// #define DEBUG_LANE_DETECTOR_SHOW_LINE_MASK
#define DEBUG_SHOW_FPS
#define SHOW_DISTANCES true
#define USE_CAN_BUS_TO_RECEIVE_SPEED true

#define MAX_SPEED_SIGN_VALID_TIME 30*60*1000
#define TIME_TO_RENOTIFY_A_SAME_TRAFFIC_SIGN 60*1000
#define OVERSPEED_WARNING_AFTER_TRAFFIC_SIGN 6 * 1000
#define OVERSPEED_WARNING_INTERVAL 15 * 1000
#define SPEED_LIMIT_VALID_TIME 15 * 60 * 1000

#define MIN_SPEED_FOR_COLLISION_WARNING 25
#define COLLISION_WARNING_INTERVAL 0.5 * 1000

#define MIN_SPEED_FOR_LANE_DEPARTURE_WARNING 20
#define LANE_DEPARTURE_WARNING_INTERVAL 1 * 1000

#define SMARTCAM_SIMULATION_LIST "data/sim_list.txt"
#define SMARTCAM_CAMERA_CALIB_FILE "data/camera_calib.txt"

#endif